# Generated by Django 5.2.6 on 2026-01-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_catalogo_model_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_model',
            name='tipo_entrega',
            field=models.IntegerField(blank=True, choices=[(1, 'Inmediata'), (2, 'Pedido')], default=1, null=True, verbose_name='Tipo de entrega'),
        ),
        migrations.AlterField(
            model_name='catalogo_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/'),
        ),
    ]
