# Generated by Django 5.2.6 on 2026-01-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_catalogo_model_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo_model',
            old_name='tipo_entrega',
            new_name='disponibilidad',
        ),
    ]
