# Generated by Django 5.2.6 on 2026-01-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_rename_tipo_entrega_catalogo_model_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_model',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogo_model',
            name='inventario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Inventario'),
        ),
    ]
