# Generated by Django 5.2.6 on 2026-02-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_catalogo_model_comentario_catalogo_model_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_model',
            name='inventario',
            field=models.IntegerField(blank=True, default=1, verbose_name='Inventario'),
        ),
    ]
