# Generated by Django 5.2.6 on 2026-02-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_catalogo_model_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoVenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de venta')),
                ('idproducto', models.IntegerField(blank=True, null=True, verbose_name='Id del producto')),
                ('cantidadVendida', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Cantidad vendida')),
                ('disponibilidad', models.IntegerField(blank=True, choices=[(1, 'Inmediata'), (2, 'Pedido')], default=1, null=True, verbose_name='Tipo de entrega')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
