# Generated by Django 5.2.6 on 2026-02-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_pedidos_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos_model',
            old_name='cantidadVendida',
            new_name='cantidad_vendida',
        ),
        migrations.RenameField(
            model_name='pedidos_model',
            old_name='codigoVenta',
            new_name='codigo_venta',
        ),
        migrations.RenameField(
            model_name='pedidos_model',
            old_name='idproducto',
            new_name='id_producto',
        ),
    ]
