# Generated by Django 5.2.6 on 2026-02-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_rename_cantidadvendida_pedidos_model_cantidad_vendida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos_model',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'En proceso'), (2, 'Finalizada'), (3, 'Cancelada')], default=1, null=True, verbose_name='Estado de la venta'),
        ),
        migrations.AddField(
            model_name='pedidos_model',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de venta'),
        ),
    ]
