# Generated by Django 5.2.6 on 2026-02-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_pedidos_model_estado_pedidos_model_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_model',
            name='cantidad_vendida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad vendida'),
        ),
    ]
