# Generated by Django 5.2.6 on 2026-02-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_alter_pedidos_model_cantidad_vendida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo_model',
            old_name='disponibilidad',
            new_name='tipo_entrega',
        ),
        migrations.RenameField(
            model_name='pedidos_model',
            old_name='disponibilidad',
            new_name='tipo_entrega',
        ),
    ]
