# Generated by Django 5.2.6 on 2026-02-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_rename_disponibilidad_catalogo_model_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_model',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Disponible'), (2, 'Reservado')], default=1, null=True, verbose_name='Estado del producto'),
        ),
    ]
