# Generated by Django 5.2.6 on 2026-02-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_catalogo_model_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_model',
            name='estado',
            field=models.IntegerField(blank=True, choices=[('D', 'Disponible'), ('R', 'Reservado')], default='D', null=True, verbose_name='Estado del producto'),
        ),
    ]
