# Generated by Django 5.2.6 on 2026-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_alter_catalogo_model_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeCookiesTem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código temporal')),
                ('producto_id', models.IntegerField(blank=True, null=True, verbose_name='Id del producto')),
                ('cantidad_prod', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de productos apartados')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
            ],
            options={
                'verbose_name': 'Temporal',
                'verbose_name_plural': 'Temporales',
            },
        ),
    ]
