# Generated by Django 5.2.6 on 2026-02-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_codecookiestem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='codeCookiesTem',
            new_name='code_cookietem_model',
        ),
    ]
