# Generated by Django 5.2.6 on 2026-02-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_rename_codecookiestem_code_cookietem_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code_cookietem_model',
            old_name='codigo_tem',
            new_name='codigo_temp',
        ),
    ]
