# Generated by Django 5.2.6 on 2026-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_rename_codigo_tem_code_cookietem_model_codigo_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='cookietem_body_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_codigo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relación codigo con tabla header')),
                ('producto_id', models.IntegerField(blank=True, null=True, verbose_name='Id del producto')),
                ('cantidad_prod', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de productos apartados')),
            ],
            options={
                'verbose_name': 'Cuerpo',
                'verbose_name_plural': 'Cuerpos',
            },
        ),
        migrations.CreateModel(
            name='cookietem_header_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_temp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código temporal')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
            ],
            options={
                'verbose_name': 'Encabezado',
                'verbose_name_plural': 'Encabezados',
            },
        ),
        migrations.DeleteModel(
            name='code_cookietem_model',
        ),
    ]
