# Generated by Django 5.2.6 on 2026-02-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_cookietem_body_model_cookietem_header_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos_model',
            name='codigo_temp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia a codigo temporal'),
        ),
    ]
