# Generated by Django 5.2.6 on 2026-05-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_pedidos_model_codigo_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos_model',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='catalogo_model',
            name='dimensiones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dimensiones'),
        ),
    ]
