# Generated by Django 5.2.6 on 2026-05-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_pedidos_model_total_alter_catalogo_model_dimensiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos_model',
            name='total',
        ),
    ]
