# Generated by Django 5.2.6 on 2026-06-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_remove_pedidos_model_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_model',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de venta'),
        ),
    ]
