# Generated by Django 5.2.6 on 2026-06-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_alter_pedidos_model_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_model',
            name='estado',
            field=models.TextField(blank=True, choices=[('D', 'Disponible'), ('R', 'Reservado'), ('A', 'Agotado')], default='D', null=True, verbose_name='Estado del producto'),
        ),
    ]
