# Generated by Django 5.2.6 on 2026-06-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codigo_recuperacion_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Codigo')),
                ('estado', models.IntegerField(blank=True, choices=[('U', 'Usado'), ('D', 'Desuso')], default='D', null=True, verbose_name='Estado de uso')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de regsitro')),
            ],
            options={
                'verbose_name': 'Recuperación',
            },
        ),
    ]
