# Generated by Django 5.2.6 on 2026-06-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo_recuperacion_model',
            name='estado',
            field=models.TextField(blank=True, choices=[('U', 'Usado'), ('D', 'Desuso')], default='D', null=True, verbose_name='Estado de uso'),
        ),
    ]
