# Generated by Django 5.2.6 on 2026-06-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_codigo_recuperacion_model_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo_recuperacion_model',
            name='estado',
            field=models.TextField(blank=True, choices=[('U', 'Usado'), ('D', 'Desuso'), ('E', 'Expirado')], default='D', null=True, verbose_name='Estado de uso'),
        ),
    ]
