# Generated by Django 5.2.6 on 2026-06-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_codigo_recuperacion_model_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo_recuperacion_model',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de regsitro'),
        ),
    ]
