# Generated by Django 5.2.6 on 2026-06-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_codigo_recuperacion_model_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo_recuperacion_model',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de regsitro'),
        ),
    ]
