# Generated by Django 5.2.6 on 2026-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_codigo_recuperacion_model_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo_recuperacion_model',
            name='periodo',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo para registro'),
        ),
    ]
